# CHUK MCP Telnet Client Configuration
host:
  name: "chuk-telnet-client"
  log_level: "INFO"

server:
  type: "stdio"  # Options: stdio, websocket

mcp_servers:
  telnet_client:
    enabled: true
    location: "."
    tools:
      enabled: true
      module: "chuk_mcp_telnet_client.tools"